#!/bin/sh

set -e 

[ "$1" =  "clean" ] && {
  rm -rf lib
  rm -rf closure
}
 
mkdir -p lib
mkdir -p closure

[ ! -f lib/clojure.jar ] && {
  echo "Fetching Clojure..."
  curl -f -O -sS http://repo1.maven.org/maven2/org/clojure/clojure/1.3.0-beta3/clojure-1.3.0-beta3.zip
  unzip -qu clojure-1.3.0-beta3.zip
  echo "Copying clojure-1.3.0-beta3/clojure-1.3.0-beta3.jar to lib/clojure.jar..."
  cp clojure-1.3.0-beta3/clojure-1.3.0-beta3.jar lib/clojure.jar
  echo "Cleaning up Clojure directory..."
  rm -rf clojure-1.3.0-beta3/
  echo "Cleaning up Clojure archive..."
  rm clojure-1.3.0-beta3.zip
}

[ ! -d closure/library ] && {
  echo "Fetching Google Closure library..."
  mkdir -p closure/library
  cd closure/library
  curl -f -O -s http://closure-library.googlecode.com/files/closure-library-20110323-r790.zip
  unzip -qu closure-library-20110323-r790.zip
  echo "Cleaning up Google Closure library archive..."
  rm closure-library-20110323-r790.zip
  cd ..
}

[ ! -d closure/compiler ] && {
  echo "Fetching Google Closure compiler..."
  mkdir -p compiler
  cd compiler
  curl -f -O -s http://closure-compiler.googlecode.com/files/compiler-latest.zip
  unzip -qu compiler-latest.zip
  echo "Cleaning up Google Closure compiler archive..."
  rm compiler-latest.zip
  cd ../..
  echo "Building lib/goog.jar..."
  echo "jar cf ./lib/goog.jar -C closure/library/closure/ goog"
  jar cf ./lib/goog.jar -C closure/library/closure/ goog
  
  echo "Copying closure/compiler/compiler.jar to lib/compiler.jar"
  cp closure/compiler/compiler.jar lib
}

[ ! -f lib/js.jar ] && {
  echo "Fetching Rhino..."
  curl -f -O -s ftp://ftp.mozilla.org/pub/mozilla.org/js/rhino1_7R3.zip
  unzip -qu rhino1_7R3.zip
  echo "Copying rhino1_7R3/js.jar to lib/js.jar..."
  cp rhino1_7R3/js.jar lib/js.jar
  echo "Cleaning up Rhino directory..."
  rm -rf rhino1_7R3/
  echo "Cleaning up Rhino archive..."
  rm rhino1_7R3.zip
}


echo "[Bootstrap Completed]"
